Development
mumani/NY-Times pull request #1
Opened 2019-01-17 23:44 UTC by newcoder171

2019-01-20 07:35 UTC, dipto0321 commented
Hi @newcoder171 and @mumani ,

You guys did a nice job 👍 . Just a couple of things you need to fix which I write down 👇 below:

1. Please try to use markdown to give a better look to your readme. You already give better info into readme. Just add a demo link of your site. 

2. [It does not look like the original site](https://prnt.sc/m9juqq). So try to fix it. It will be a little bit tricky. But trust me, it will be fun. I know that you can do it. You have that ability 😃 🍾 🎉 .

3. ` Bad value ./image/NYT Logo.png for attribute src on element img: Illegal character in path segment: space is not allowed.` You can find a lot of error's like this when you will check your site with w3validator. So check it and fix all issues.

4. Put your `main.css` file inside `css` folder and link it to your `.html` file.

5. There is some merge conflict issue with your master branch. So after fixing this or before fixing try to resolve it.

I think except those ☝️ all are good. The code is clean with indentation. Try to build a habit of comment ( should be meaningful ) in your code from your future project.

Please use [w3validator](https://validator.w3.org) and [CSS lint](http://csslint.net/) and try to fix all issues.

**Note:** After fixing, I think you can merge it into the master or if you want to review it again then make e review request again. Best of luck 😄

2019-01-30 00:53 UTC, heyapricot requested changes
# You are almost there
So close! There is a good amount of details that need to be fixed so I have to ask you again to work on those and submit a new code review request when you are finished. Thank you for your perseverance! Please address the comments, and after that submit a new code review request.

Additional comments:
Check the alignment of the navbar's content
![screen shot 2019-01-29 at 18 15 29](https://user-images.githubusercontent.com/14355495/51950656-f3c1c480-23f6-11e9-9aad-9d831166c927.png)

Check the alignment of this section
![screen shot 2019-01-29 at 18 24 02](https://user-images.githubusercontent.com/14355495/51950670-076d2b00-23f7-11e9-95c6-102a2371d315.png)



Tips:
For every HTML/CSS projects please check your files with the [W3 Validator](https://validator.w3.org) and the [CSS Linter](http://csslint.net/)

2019-01-30 00:53 UTC, heyalvaro commented on index.html
> +                <figcaption><strong>THE UNIVERSE</strong> is just under 14 billion years old. From our position in the
Element `figcaption` not allowed as child of element div in this context. Fix all the occurrences

2019-01-30 00:53 UTC, heyalvaro commented on index.html
> +                <span>Editors' Pick</span>
Element `span` not allowed as child of element `ul` in this context

2019-01-30 00:53 UTC, heyalvaro commented on index.html
> +                <hr>
Element `hr` not allowed as child of element `ul` in this context.

2019-01-30 00:53 UTC, heyalvaro commented on index.html
> +        <img alt="" class="img5" src="https://static01.nyt.com/images/2014/03/18/science/space/18cosmos-2/18cosmos-2-articleLarge.jpg?"
Here, for the `width` property you don't have to add `px`. Remove `px`

2019-01-30 00:53 UTC, heyalvaro commented on index.html
> +        <img src="./image/NYT Logo.png" alt="logo" height="25">
`space` is not allowed in paths. Check the `./image/NYT Logo.png` path

2019-01-30 00:53 UTC, heyalvaro commented on index.html
> +                <hr style="margin-bottom: 8px">
Element `hr` not allowed as child of element `ul` in this context.

2019-01-30 00:53 UTC, heyalvaro commented on css/main.css
> +hr {
Don't duplicate selectors. You used this one first on line 82

2019-01-30 00:53 UTC, heyalvaro commented on index.html
> +    <hr>
Is this `hr` element doing anything?

2019-01-30 00:53 UTC, heyalvaro commented on index.html
> +        <div>
The width of this element is different from the original

2019-01-30 00:53 UTC, heyalvaro commented on index.html
> +            <p style="text-align: center">March 17, 2014</p>
The author and the date are not aligned to the center in the original article. Also, watch the spaces (And don't use `br` for spacing. Use CSS)

2019-01-30 00:53 UTC, heyalvaro commented on index.html
> +        <h2><strong>‘As Big as It Gets’</strong></h2>
The original has space in the top and the bottom

2019-01-30 00:53 UTC, heyalvaro commented on index.html
> +        <p>Gravity waves are the latest and deepest secret yet pried out of the cosmic microwaves, which were
You missed a header before this

2019-01-30 00:53 UTC, heyalvaro commented on index.html
> +        <img alt="" class="img5" src="https://static01.nyt.com/images/2014/03/18/science/space/18cosmos-2/18cosmos-2-articleLarge.jpg?"
Also, make the width match the origina

2019-01-30 00:53 UTC, heyalvaro commented on index.html
> +        <p>A Special Time</p>
This should be a header

2019-01-30 00:53 UTC, heyalvaro commented on index.html
> +            <button class="s-icons"><i class="material-icons">reply</i></button>
Icons are not centered

2019-01-30 00:53 UTC, heyalvaro commented on index.html
> +            <br /><br /><br>
Don't add multiple `br` elements for spacing. If you want to add spacing do it through CSS

2019-01-30 00:53 UTC, heyalvaro commented on index.html
> +        <div class="footer">
You are missing the NY Times image, the font should be sans-serif and the icons are repeated

2019-02-28 14:08 UTC, dipto0321 commented
Hi @newcoder171  and @mumani ,
1. Please check these [errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Fraw.githack.com%2Fmumani%2FNY-Times%2Fdevelopment%2Findex.html). and fix it. Again check with [w3Validator](https://validator.w3.org/).
2. I found some resoulation based problem. especially on the alignment with the nav bar logo as mentioned before. (Use the zoom in and out in your browser to understand the problem). 
![nav_portion](https://user-images.githubusercontent.com/6507903/53570728-64dccf00-3b91-11e9-8884-c0d9589ac05d.jpg)
![big_portion](https://user-images.githubusercontent.com/6507903/53570736-6908ec80-3b91-11e9-9d88-16e15d7b02b9.jpg)

After those changes, you can merge it into master. Don't need to request for any code review. But if you want to you can.

Let me know if you have any question.

Thanks

2019-03-08 20:50 UTC, merged